config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#delete'

  resources :clients do
    get '/upcoming-events', to: 'clients#upcoming_events'
    get '/past-events', to: 'clients#past_events'
  end

  resources :events do
    resources :reviews, only: [:index, :create]
  end
  
  resources :venues
  resources :vendors, only: [:index, :show]
  resources :reviews, only: [:create]
  resources :event_vendors, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :events
  has_many :venues, through: :events
  has_many :vendors, through: :events

	has_secure_password

  validates_presence_of :first_name, :last_name, :username, :password, :password_confirmation
	validates :username, uniqueness: true
	
	def all_events
		Event.all.select { |event| event.client == self }
	end

	def upcoming_events
		all_events.select { |event| event.date >= Date.today }
	end

	def past_events
		all_events.select { |event| event.date < Date.today }
	end

end

app/models/event.rb
class Event < ApplicationRecord
    attr_accessor :first_vendor_id, :second_vendor_id, :third_vendor_id

    belongs_to :client
    belongs_to :venue
    has_many :reviews
    has_many :event_vendors
    has_many :vendors, through: :event_vendors
    validates :title, presence: true
    accepts_nested_attributes_for :event_vendors


    def latest_reviews
        self.reviews.limit(5)
    end
end

app/models/event_vendor.rb
class EventVendor < ApplicationRecord
    belongs_to :event 
    belongs_to :vendor
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :event
end

app/models/vendor.rb
class Vendor < ApplicationRecord
    has_many :event_vendors
    has_many :events, through: :event_vendors

    def self.cater
        all.where(category: "Catering")
    end

    def self.music
        all.where(category: "Music")
    end

    def self.decor
        all.where(category: "Decor")
    end
end

app/models/venue.rb
class Venue < ApplicationRecord
    has_many :events
    has_many :clients, through: :events
    has_many :vendors, through: :events
    has_many :reviews, through: :events

    def self.search(search)
        if search
            self.where("capacity > ?", search)
        else
            self.all 
        end
    end

    def self.featured_venue
        self.all.max_by{|venue| venue.events.count}
    end

    def self.logan
        Venue.where(location: "Logan Square")
    end

    def self.river
        Venue.where(location: "River North")
    end

    def self.west
        Venue.where(location: "West Side")
    end

    def latest_events
        self.events.limit(10)
    end

    def all_events
        self.events
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  def home
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authorize, except: [:new, :create]
  before_action :find_client, except: [:new, :create]
  
  def show
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.valid?
      @client.save
      redirect_to client_path(@client)
    else
      flash[:errors] = @client.errors.full_messages
      redirect_to new_client_path
    end
  end

  def edit
  end
  
  def update
    if @client.update(client_params)
      redirect_to client_path(@client)
    else
      flash[:errors] = @client.errors.full_messages
      redirect_to edit_client_path(@client)
    end
  end

  def destroy
    @client.destroy
    redirect_to root_path
  end

  def upcoming_events
  end

  def past_events
  end

  private

  def find_client
    if check_id(params[:id])
      @client = Client.find(params[:id])
    else
      redirect_to client_path(current_client)
    end
  end

  def client_params
    params.require(:client).permit(:username, :password, :password_confirmation, :first_name, :last_name, :location)
  end

end

app/controllers/event_vendors_controller.rb
class EventVendorsController < ApplicationController

    def create
        @event_vendor = EventVendor.create(event_vendor_params)
        redirect_to show_events_path(params[:event_id])
    end

    private

    def event_vendor_params
        params.require(:event_vendor).permit(:vendors[:vendor_id], :event_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_action :authorize, except: :show
before_action :set_event, except: [:new, :create]

    def new
        @event = Event.new
    end

    def create
        @event = Event.new(params.require(:event).permit(:client_id, :venue_id, :title, :event_type, :date, :approved))
        if @event.save
            redirect_to @event
        else
            flash[:errors] = @event.errors.full_messages
            redirect_to new_event_path
        end
    end

    def show
    end

    def edit
        redirect_to @event unless current_client.id == @event.client_id
    end

    def update
        if @event.update(update_event_params)
            redirect_to @event
        else
            flash[:errors] = @event.errors.full_messages
            redirect_to edit_event_path
        end
    end

    def destroy
        @event.delete
        redirect_to root_path
    end

    private

    def event_params
        params.require(:event).permit(:client_id, :venue_id, :title, :event_type, :date, :approved)
    end

    def update_event_params
        vendor_ids = [params[:event][:first_vendor_id], params[:event][:second_vendor_id], params[:event][:third_vendor_id]]
        update_params = params.require(:event).permit(:title, :event_type, :date, :approved)
        update_params[:vendor_ids] = vendor_ids
        return update_params
    end

    def set_event
        @event = Event.find(params[:id])
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def new
        @review = Review.new
    end

    def create
        @review = Review.create(review_params)
        redirect_to event_reviews_path(params[:event_id])
    end

    def index
        @event = Event.find(params[:event_id])
        @event_reviews = @event.reviews
        @review = Review.new(event_id: @event.id)
    end

    private

    def review_params
        params.require(:review).permit(:title, :event_id, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    @client = Client.find_by(username: params[:username])
    @client && @client.authenticate(params[:password]) ? login_success : login_failure
  end

  def delete
    session.delete(:client_id)
    redirect_to login_path
  end

  private

  def login_success
    session[:client_id] = @client.id
    redirect_to client_path(@client)
  end

  def login_failure
    flash[:notice] = "Incorrect username and/or password"
    redirect_to login_path
  end

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

    def index
        @vendors = Vendor.all
    end

    def show
        @vendor = Vendor.find(params[:id])
    end
    
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
    before_action :find_venue, only: [:show]

    def index
        @venues = Venue.search(params[:search])
    end

    def show
        render :layout => 'venues/show'
    end

    private
    
    def venue_params
        params.require(:venue).permit(:name, :location, :capacity, :type, :search)
    end

    def find_venue
        @venue = Venue.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_client
    Client.find_by(id: session[:client_id])
  end

  def logged_in?
    !!current_client
  end

  def authorize
      flash[:notice] = "Please log in to continue!"
      redirect_to login_path
      unless logged_in?
    end
  end

  def check_id(id)
    id.to_i == current_client.id
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/event_vendors_helper.rb
module EventVendorsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/application/home.html.erb
<div class= 'welcome'>
<h1>WELCOME!</h1>
<p>Eventsaholic has been Chicagoland's premier online event booking system since 1999.</p> 
<p>Join us and make your events spectacular!</p>
</div>
<br>
<br>

app/views/clients/_form.html.erb
<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <b>***<%= error %>***</b><br>
    <% end %>
<% end %>
<%= form_with model: @client do |f| %>
<div class="container">
  <div class="panel-body">
    <form role="form">
        <div class="row">
          <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
              <%= f.label :first_name %>
              <%= f.text_field :first_name %><br>
            </div>
          </div>
          
          <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
              <%= f.label :last_name %>
              <%= f.text_field :last_name %><br>
            </div>
          </div>
        </div>
      <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6">
          <div class="form-group">
            <%= f.label :location %>
            <%= f.text_field :location %><br>
          </div>
        </div>
      
        <div class="col-xs-6 col-sm-6 col-md-6">
          <div class="form-group">
            <%= f.label :username %>
            <%= f.text_field :username %><br>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6">
          <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password %><br>
          </div>
        </div>

          <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
              <%= f.label :password_confirmation %>
              <%= f.password_field :password_confirmation %><br>
            </div>
          </div>
        </div>

      <%= f.submit "Submit", class:"btn btn-info btn-lg" %>
    <% end %>
  </div>
  </form>
</div>

app/views/clients/edit.html.erb
<div class='client_form'>

<h1>Edit Profile</h1>

<%= render 'form'%>
<br>
<%= link_to('Delete Account', client_path(@client), method: :delete, class:'btn btn-danger') %>
</div>

app/views/clients/new.html.erb
<div class='client_form'>
<h1>Sign Up</h1>

<%= render 'form'%>

</div>

app/views/clients/past_events.html.erb
<h1>Your Past Events</h1>

<% @client.past_events.each do |event| %>
  <%= link_to(event.title, event_path(event)) %><br>
  <% end %>

app/views/clients/show.html.erb
<h1><%= "Hello, #{@client.first_name}!" %></h1>

Upcoming Events: 
<ul>
<% @client.upcoming_events.each do |event| %>
 <li> <%= link_to(event.title, event_path(event)) %></li>
  <% end %>
  </ul>
Past Events:
<ul>
<% @client.past_events.each do |event| %>
 <li> <%= link_to(event.title, event_path(event)) %></li>
  <% end %>
</ul>

<%= button_to('Edit Profile', edit_client_path(@client), method: :get, class:'btn submit')%>
<br>
<%= button_to('Logout', logout_path, method: :delete, class:'btn submit') %>

app/views/clients/upcoming_events.html.erb
<h1>Your Upcoming Events</h1>

<% @client.upcoming_events.each do |event| %>
  <%= link_to(event.title, event_path(event)) %><br>
  <% end %>

app/views/event_vendors/_form.html.erb
<%= form_for @event do |f| %>
        <%= f.label "Catering" %>
        <%= f.collection_select :first_vendor_id, Vendor.cater, :id, :name, include_blank: true %><br>

        <%= f.label "Music" %>
        <%= f.collection_select :second_vendor_id, Vendor.music, :id, :name, include_blank: true %><br>

        <%= f.label "Decor" %>
        <%= f.collection_select :third_vendor_id, Vendor.decor, :id, :name, include_blank: true %><br>
<%= f.submit "Add Vendors" %>
<% end %>

app/views/events/_form.html.erb
<%= form_with model: @event do |f|%>
<%= f.hidden_field(:client_id, value: current_client.id) %>
<%= f.label "Event Title" %>
<%= f.text_field :title %><br>
<%= f.label "Occasion" %>
<%= f.text_field :event_type %><br>
<%= f.label "Venue" %>
<%= f.collection_select :venue_id, Venue.all, :id, :name, include_blank: true %><br>
<%= f.label :date %>
<%= f.date_select(:date) %><br>
<%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Your Event</h1>
<% if flash[:errors] %>
    <% flash[:errors].each do |err| %>
    <b>*<%= err %>*</b><br>
    <% end %>
<% end %>

<%= render 'form' %>
<br>
<%= button_to "Delete Event", :method=> :delete %>
<br>
<h3>Add Vendors</h3>
<%= render 'event_vendors/form' %>

app/views/events/new.html.erb
<h1>Request an Event</h1>
<% if flash[:errors] %>
    <% flash[:errors].each do |err| %>
    <b>*<%= err %>*</b><br>
    <% end %>
<% end %>
<%= render 'form' %>

app/views/events/show.html.erb
<h1><%= @event.title  %></h1>
<p>Status: <%= @event.approved ? "Booked" : "Pending Approval" %>
<p><%= @event.date %></p>
<p>Host: <%= @event.client.first_name + ' ' + @event.client.last_name %></p>
<p>Venue: <%= link_to @event.venue.name, venue_path(@event.venue) %></p>
<p>Occasion: <%= @event.event_type %></p>
<% @event.vendors.each do |vendor| %>
<p><%= vendor.category %> provided by: <%= vendor.name %></p>
<% end %>

<% if current_client && current_client.id == @event.client_id %>
<%= link_to "Edit Event", edit_event_path %>
<% end %>
<br>
<h3>Latest Reviews: </h3>
<% @event.latest_reviews.each do |review| %>
<h4><%= review.title %></h4>
<div class= 'review_content'>
<p><%=review.content %></p>
</div>
<% end %>

<%= link_to "See all reviews", event_reviews_path(@event) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventsaholic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <style>
      body {
        background-color: whitesmoke;
      }
    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class='navbar'>
  <%= link_to "Home", root_path, class: "nav_link" %> <%= link_to "Sign Up", new_client_path, class: "nav_link" %>   <%= link_to "Log In", login_path, class: "nav_link" %>
  </div>
  <div class='banner'>
  <br>
    <h1 style= "font-size: 55px">Eventsaholic</h1>
    <h3 style= "font-size: 20px">Chicago's event planner</h3>
  </div>
  <div class='menu_bar'>
    <%= link_to "Browse Venues", venues_path, class: "menu_link" %>
    <%= link_to "Browse Vendors", vendors_path, class: "menu_link" %>
    <%= link_to "Book Event", new_event_path, class: "menu_link" %>
    <% if current_client %>
      <%= link_to "Client Page", client_path(current_client), class: "menu_link" %>
    <% end %>

  </div>
    <br>
  <div class= 'page_view'>
    <%= yield %>
  </div>

<div class= 'buffer'>
</div>
<div class='footer'>
  <p>©2019, DanSarNav Inc.
</div>
  </body>
</html>

app/views/layouts/venues/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventsaholic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <style>
      body {
        background-color: whitesmoke;
      }
    </style>
    <%# <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css"> %>
    <%# <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script> %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class='navbar'>
  <%= link_to "Home", root_path, class: "nav_link" %> <%= link_to "Sign Up", new_client_path, class: "nav_link" %>   <%= link_to "Log In", login_path, class: "nav_link" %>
  </div>

    <% if @venue.venue_type == "Bar" %>
        <div class="venue_background1" ></div>
    <%elsif @venue.venue_type == "Restaurant" %>
        <div class="venue_background2" ></div>
    <%else%>
        <div class="venue_background3"></div>
    <% end %>

  <div class='menu_bar'>
  <%= link_to "Browse Venues", venues_path, class: "menu_link" %>
  <%= link_to "Browse Vendors", vendors_path, class: "menu_link" %>
  <%= link_to "Book Event", new_event_path, class: "menu_link" %>
  <% if current_client %>
    <%= link_to "Client Page", client_path(current_client), class: "menu_link" %>
  <% end %>
  </div>
<br>
<div class= 'page_view'>
    <%= yield %>
</div>
  <br>
  <br>
  <br>
  <br>
  <div class='footer'>
  <p>©2019, DanSarNav Inc.
  </div>
  </body>
</html>

app/views/reviews/index.html.erb
<h1><%= @event.title %></h1>

<h3>Create Review:</h3>
<%= form_for([@event, @review])do |f| %>
<%= f.hidden_field :event_id, value: @event.id %>
<%= f.label :title %>
<%= f.text_field :title %> <br>
<%= f.label :content %> <br>
<%= f.text_area :content %> <br>
<%= f.submit "Create Review" %>
<% end %>


<p>Reviews:</p>

<% @event_reviews.each do |review| %>
<div class="shadow-lg p-3 mb-5 bg-lightgrey rounded">
    <h3><%= review.title %></h3>
    <p><%= review.content %></p>
    </div>
    
<% end %>

app/views/vendors/_form.html.erb
<%= form_with model: @event_vendor do |f| %>

app/views/vendors/index.html.erb
<div class= 'row'>
    <div class= 'column'>
        <h2>Catering</h2>
        <% @vendors.cater.each do |vendor| %>
        <%= link_to vendor.name, vendor %><br>
        <% end %>
        <br>
    </div>

    <div class= 'column'>
        <h2>Music</h2>
        <% @vendors.music.each do |vendor| %>
        <%= link_to vendor.name, vendor %><br>
        <% end %>
    <br>
    </div>
    <div class= 'column'>
        <h2>Decoration</h2>
        <% @vendors.decor.each do |vendor| %>
        <%= link_to vendor.name, vendor %><br>
        <% end %>
        <br>
    </div>
</div>

app/views/vendors/show.html.erb
<h1><%= @vendor.name %></h1>
Category: <%= @vendor.category %><br><br>
Recent Events:

<br>
<br>
<% if @vendor.name == "Ezcater" %>
<div class="row">
<div class="col-sm-4 mb20"><img class="img-fluid m-x-auto d-block img-responsive" src="http://twelvebasketscatering.com/wp-content/uploads/2018/12/Vey-182108-80.jpg" alt=""></div>
<div class="col-sm-4 mb20"><img class="img-fluid m-x-auto d-block img-responsive" src="https://tastefuldinners.com/wp-content/uploads/2016/08/Catering-01.jpg" alt=""></div>
<div class="col-sm-4 mb20"><img class="img-fluid m-x-auto d-block img-responsive" src="https://dinebydesign.net/wp-content/uploads/2019/04/1015161612-1-4.jpg" alt=""></div>
</div>
<% end %>

app/views/venues/index.html.erb
<h2>Featured Venue: <%= link_to Venue.featured_venue.name, venue_path(Venue.featured_venue)%> </h2>

<div class="row">   
    <div class="column">
        <h3>Venues in Logan Square:</h3>
        <% @venues.logan.each do |venue| %>
        <p><%= link_to venue.name, venue_path(venue) %></p>
        <% end %>
    </div>

    <div class="column">
        <h3>Venues in River North:</h3>
        <% @venues.river.each do |venue| %>
        <p><%= link_to venue.name, venue_path(venue) %></p>
        <% end %>
     </div>

    <div class="column">
        <h3>Venues in West Side:</h3>
        <% @venues.west.each do |venue| %>
        <p><%= link_to venue.name, venue_path(venue) %></p>
        <% end %>
    </div>
</div>


<%= form_tag(venues_path, method: :get) do %>
<p>Search venue by capacity: </p>
<%= text_field_tag :search %>
<%= submit_tag "Search", name: nil, class:'btn submit' %>
<% end %>

app/views/venues/show.html.erb
<%= image_tag @venue.logo, class:"venue_logo" %>

<p>Type: <%= @venue.venue_type %></p>
<p>Capacity: <%= @venue.capacity %></p>
<p>Location: <%= @venue.location %></p> 
<br>
<br>
<h3>Recent events:</h3>
    <ul>
    <% @venue.latest_events.each do |event| %>
        <li><%= link_to event.title, event_path(event)%></li>
    <% end %>
    </ul>


<h3>Reviews: </h3>

<% @venue.all_events.each do |event| %>
    <% event.reviews.each do |review|%>
    <p><b><%= review.title %></b></p>
    <div class='review_content'>
    <p><%=   review.content %></p>
    </div>
    <% end %>
<% end %>
</div>